cc_library(
    name = "module_c",
    srcs = ["module_c.cc"],
    hdrs = ["module_c.h"],
)

cc_test(
    name = "module_c_test",
    srcs = ["module_c_test.cc"],
    deps = [
        ":module_c",
    ],
)
